/** Al ordlyd i farvebehandlingens brugerflade. Ret her uden at røre layoutet. */
export const TEXT = {
  title: 'Farvebehandling',
  back: 'Tilbage til forsiden',
  loading: 'Indlæser farvebehandling …',
  tabs: { training: 'Træning', practice: 'Selvvalgt', analysis: 'Analyse' },
  comingSoon: (name: string) => `${name} kommer i næste version. Indtil da kan du se alle kombinationer i Analyse.`,

  problem: 'Problemet',
  lines: 'Linjerne',
  difference: 'Forskellen',
  details: 'Sidningerne',
  north: 'Nord · bordet',
  south: 'Syd · dig',
  west: 'Vest',
  east: 'Øst',
  unknown: '?',
  suit: '♠',
  goalLabel: 'Mål',
  goal: (n: number) => `${n} stik`,
  firstLead: (text: string) => `Første udspil: ${text}`,
  assumptions: 'a priori · ubegrænsede forbindelser · optimalt modspil',

  line: (letter: string) => `Linje ${letter}`,
  best: '✓ bedst',
  equal: 'lige god',
  mixed: 'Chancen kræver, at du blander mellem to linjer.',
  chanceOf: (goal: number) => `Chance for ${goal} stik`,

  reaches: 'målet nås',
  misses: 'målet nås ikke',
  hit: '✓',
  miss: '✕',
  legend: 'Hvert felt er en sidning; bredden er chancen.',
  disagree: (n: number, list: string, more: number) =>
    `Linjerne er uenige i ${n === 1 ? '1 sidning' : `${n} sidninger`}: ${list}${more ? ` og ${more} til` : ''}.`,
  agree: 'Linjerne giver samme resultat i alle sidninger.',
  decisive: 'De afgørende sidninger',
  groupBy: 'Gruppér',
  byDistribution: 'fordeling',
  byHonors: 'honnører',
  showAll: 'Vis alle sidninger',
  showFewer: 'Vis kun de afgørende',
  layout: (west: string, east: string) => `Vest ${west} – Øst ${east}`,
  fieldLabel: (west: string, east: string, chance: string, result: string) => `Vest ${west}, Øst ${east}: ${chance}, ${result}`,
  selected: 'Valgt sidning',

  result: 'Resultatet',
  bestChance: (goal: number, letter: string, chance: string) => `Bedste chance for ${goal} stik: ${chance} med linje ${letter}.`,
  pairs: (tricks: string, text: string) => `Bedst i parturnering: ${text} (${tricks} stik i gennemsnit).`,
  frequency: 'Hvor tit?',
  combination: (text: string) => `Kombinationen: ${text}.`,
  situation: (cards: number, text: string) => `Es og konge uden damen med ${cards} kort: ${text}.`,
  verified: 'Tallene stemmer med bridgehands.com.',
  unverified: 'Tallene afviger fra bridgehands.com; se valideringsrapporten.',

  choose: 'Vælg kombination',
  bank: 'Banken',
  bankHelp: 'Damen mangler. Hyppigste først.',
  picker: 'Kortvælger',
  pickerHelp: 'Tryk på et kort én gang for bordet, to gange for din hånd og tre gange for at fjerne det.',
  pickerCard: (card: string, owner: string) => `${card}: ${owner}`,
  owners: { none: 'ingen', N: 'bordet', S: 'din hånd' },
  clear: 'Ryd',
  notInBank: 'Kombinationen findes ikke i banken endnu. Fase 2 regner vilkårlige kombinationer.',
  pickMore: 'Vælg kort til bordet og din hånd.',
  bankEntry: (rank: number, holding: string, often: string) => `${rank}. ${holding} · ${often}`,
} as const;
