/** Al ordlyd i farvebehandlingens brugerflade. Ret her uden at røre layoutet. */
export const TEXT = {
  title: 'Farvebehandling',
  back: 'Tilbage til forsiden',
  backToTraining: 'Tilbage til Træning',
  loading: 'Indlæser farvebehandling …',
  loadFailed: 'Banken kunne ikke hentes. Prøv igen, når du er online.',
  tabs: { training: 'Træning', practice: 'Selvvalgt', analysis: 'Analyse' },

  problem: 'Problemet',
  lines: 'Linjerne',
  difference: 'Forskellen',
  details: 'Sidningerne',
  north: 'Nord · bordet',
  south: 'Syd · dig',
  west: 'Vest',
  east: 'Øst',
  unknown: '?',
  suit: '♠',
  goalLabel: 'Mål',
  goal: (n: number) => `${n} stik`,
  firstLead: (text: string) => `Første udspil: ${text}`,
  assumptions: 'a priori · ubegrænsede forbindelser · optimalt modspil',

  line: (letter: string) => `Linje ${letter}`,
  best: '✓ bedst',
  equal: 'lige god',
  mixed: 'Chancen kræver, at du blander mellem to linjer.',
  chanceOf: (goal: number) => `Chance for ${goal} stik`,

  reaches: 'målet nås',
  misses: 'målet nås ikke',
  hit: '✓',
  miss: '✕',
  legend: 'Hvert felt er en sidning; bredden er chancen.',
  disagree: (n: number, list: string, more: number) =>
    `Linjerne er uenige i ${n === 1 ? '1 sidning' : `${n} sidninger`}: ${list}${more ? ` og ${more} til` : ''}.`,
  agree: 'Linjerne giver samme resultat i alle sidninger.',
  decisive: 'De afgørende sidninger',
  groupBy: 'Gruppér',
  byDistribution: 'fordeling',
  byHonors: 'honnører',
  showAll: 'Vis alle sidninger',
  showFewer: 'Vis kun de afgørende',
  layout: (west: string, east: string) => `Vest ${west} – Øst ${east}`,
  fieldLabel: (west: string, east: string, chance: string, result: string) => `Vest ${west}, Øst ${east}: ${chance}, ${result}`,
  selected: 'Valgt sidning',

  result: 'Resultatet',
  bestChance: (goal: number, letter: string, chance: string) => `Bedste chance for ${goal} stik: ${chance} med linje ${letter}.`,
  pairs: (tricks: string, text: string) => `Bedst i parturnering: ${text} (${tricks} stik i gennemsnit).`,
  frequency: 'Hvor tit?',
  combination: (text: string) => `Kombinationen: ${text}.`,
  situation: (label: string, cards: number, text: string) => `${label} med ${cards} kort: ${text}.`,
  /** Situationen bag kombinationen, fx "Es og konge uden damen" eller "Uden esset". */
  situationLabel: (ours: readonly number[], theirs: readonly number[]) => {
    const some: Record<number, string> = { 14: 'es', 13: 'konge', 12: 'dame', 11: 'knægt' };
    const the: Record<number, string> = { 14: 'esset', 13: 'kongen', 12: 'damen', 11: 'knægten' };
    const names = ours.map((r) => some[r]);
    const list = names.length > 1 ? `${names.slice(0, -1).join(', ')} og ${names[names.length - 1]}` : (names[0] ?? '');
    const capital = (t: string) => t.charAt(0).toUpperCase() + t.slice(1);
    if (!theirs.length) return capital(list);
    return list ? `${capital(list)} uden ${the[theirs[0]]}` : `Uden ${the[theirs[0]]}`;
  },
  verified: 'Tallene stemmer med bridgehands.com.',
  unverified: 'Tallene afviger fra bridgehands.com; se valideringsrapporten.',

  choose: 'Vælg kombination',
  bank: 'Banken',
  bankHelp: 'Alle sider fra bridgehands.com, hyppigste først.',
  pageFilter: 'Modpartens honnørpoint',
  hp: (points: number) => (points === 0 ? 'ingen' : `${points} hp`),
  picker: 'Kortvælger',
  pickerHelp: 'Tryk på et kort én gang for bordet, to gange for din hånd og tre gange for at fjerne det.',
  pickerCard: (card: string, owner: string) => `${card}: ${owner}`,
  owners: { none: 'ingen', N: 'bordet', S: 'din hånd' },
  clear: 'Ryd',
  notInBank: 'Kombinationen findes ikke i banken endnu. Fase 2 regner vilkårlige kombinationer.',
  pickMore: 'Vælg kort til bordet og din hånd.',
  bankEntry: (rank: number, holding: string, often: string) => `${rank}. ${holding} · ${often}`,

  // Træning
  streak: 'Streak',
  daysInRow: (n: number) => (n === 1 ? 'dag i træk' : 'dage i træk'),
  xp: 'XP',
  today: 'I dag',
  todayPlan: (due: number, fresh: number) =>
    `${due === 1 ? '1 emne' : `${due} emner`} til repetition · ${fresh === 1 ? '1 ny kombination' : `${fresh} nye kombinationer`}`,
  doneToday: 'Dagens session er gennemført. Du kan tage en til.',
  ownTrack: 'Farvebehandling har sin egen streak og XP, adskilt fra fordelingssporet.',
  start: 'Start dagens session',
  palace: 'Paladset',
  data: 'Dine data',
  phases: { repetition: 'Repetition', niveau: 'Niveau', lynrunde: 'Lynrunde', status: 'Status' },
  sessionMeta: (xp: number, combo: number) => `${xp} XP${combo >= 2 ? ` · combo ${combo}` : ''}`,
  stop: 'Afbryd sessionen',

  // Opgaverne
  goalPrompt: (n: number) => `Mål: ${n} stik`,
  chooseLine: 'Vælg linjen',
  guessPrompt: (n: number) => `Hvor stor er chancen for ${n} stik?`,
  guessOptional: 'Gæt chancen (valgfrit)',
  intervals: ['under 25 %', '25–50 %', '50–75 %', '75–100 %'],
  answer: 'Svar',
  theLine: 'Linjen',
  pickBest: 'Tryk på den bedste linje',
  newGoal: (before: number, now: number) => `Før var målet ${before} stik. Nu skal du have ${now} stik.`,
  findHole: 'Hvor taber linjen? Vælg sidningen.',
  whatNow: 'Hvad nu?',
  firstRound: 'Første runde',
  guessNow: (n: number) => `Hvor stor er chancen nu for ${n} stik?`,
  seats: { N: 'Nord', Ø: 'Øst', S: 'Syd', V: 'Vest' },
  posteriorNote: 'Båndet viser kun de sidninger, der stadig er mulige, med deres chance efter første runde. Lagde en modspiller ét af to ligeværdige kort, tæller den sidning kun halvt (begrænset valg).',
  counting: 'Optællingen',
  countingHelp: 'Modspillerne har vist deres længder i de tre andre farver.',
  shown: (seat: string, suits: string, vacant: number) => `${seat}: ${suits} – ${vacant === 1 ? '1 ledig plads' : `${vacant} ledige pladser`}`,
  countingNote: 'Chancerne regnes med de ledige pladser.',
  suitSymbols: ['♠', '♥', '♦', '♣'],

  // Facit
  right: 'Rigtigt',
  half: 'Halvt rigtigt',
  wrong: 'Forkert',
  goodDecision: 'God beslutning.',
  halfDecision: 'Rigtig linje – chancen ligger i et andet interval.',
  betterLine: (letter: string) => `Linje ${letter} giver mere her.`,
  yourLine: (letter: string, ok: boolean) => `Du valgte linje ${letter} ${ok ? '✓' : '✕'}`,
  bestLine: (letter: string, chance: string) => `Bedst: linje ${letter} – ${chance}`,
  yourGuess: (interval: string, ok: boolean) => `Dit gæt: ${interval} ${ok ? '✓' : '✕'}`,
  noGuess: 'Intet gæt',
  chanceIs: (chance: string, interval: string) => `Chancen er ${chance}, altså ${interval}.`,
  holeIs: (layout: string) => `Linjen taber, når ${layout}.`,
  yourHole: (layout: string, ok: boolean) => `Dit valg: ${layout} ${ok ? '✓' : '✕'}`,
  gained: (xp: number, combo: number) => `+${xp} XP${combo >= 2 ? ` · ${combo} rigtige i træk` : ''}`,
  yourChoice: 'dit valg',
  why: 'Hvorfor →',
  back2: '← Facit',
  next: 'Næste opgave',
  memory: 'Huskeregel',
  image: 'Billede',
  room: (name: string, station: number | null) => (station ? `Rum: ${name} · station ${station}` : `Rum: ${name}`),
  scene: 'Din scene',
  allLayouts: 'Alle sidninger',

  // Introduktion
  newCombination: 'Ny kombination',
  goalsText: (goals: readonly number[]) => `Mål: ${goals.map((g) => `${g} stik`).join(' og ')}`,
  newStation: (name: string, station: number) => `Rum: ${name} · ny station ${station}`,
  tryIt: 'Prøv den',

  // Status
  sessionDone: 'Dagens session er færdig',
  sessionScore: (correct: string, total: number) => `${correct} af ${total} rigtige`,
  sessionXp: (xp: number) => `+${xp} XP i dag`,
  tomorrow: (n: number) => `I morgen: ${n === 1 ? '1 emne' : `${n} emner`} til repetition.`,
  toHome: 'Færdig',

  // Selvvalgt
  practiceTitle: 'Vælg selv',
  practiceHelp: 'Øv det, du vil. Svarene logges, men ændrer ikke dagsplanen. Facit vises, når du har valgt linje.',
  filters: { technique: 'Teknik', cards: 'Antal kort', missing: 'Manglende honnører', goal: 'Mål' },
  all: 'Alle',
  option: (label: string, count: number) => `${label} (${count})`,
  cardsOption: (n: number) => `${n} kort`,
  goalOption: (n: number) => `${n} stik`,
  noHonors: 'ingen',
  startPractice: (n: number) => `Start · ${n === 1 ? '1 kombination' : `${n} kombinationer`}`,
  changeFilter: 'Skift filter',

  // Paladset
  palaceHelp: 'Hvert rum er en teknik, og stationerne er kombinationerne i den rækkefølge, du har mødt dem.',
  closedRooms: 'Lukkede rum',
  closedHelp: 'Et rum åbner, når dets første kombination dukker op i Træning.',
  edit: 'Ret',
  save: 'Gem',
  cancel: 'Annullér',
  standard: 'standard',
  own: 'dit eget',
  resetHint: 'Tom tekst giver standarden tilbage.',
  noScene: 'Ingen scene endnu.',
  editLabel: (what: string) => `Ret ${what.toLowerCase()}`,

  // Dine data
  dataHelp: 'Farvebehandling gemmer alt i din browser under sin egen nøgle. Fordelingssporets data røres ikke.',
  exportData: 'Eksportér',
  importData: 'Importér',
  importFile: 'Vælg fil',
  importSummary: (xp: number, items: number, sessions: number, streak: number) =>
    `Filen har ${xp} XP, ${items} emner, ${sessions} sessioner og en streak på ${streak}.`,
  replace: 'Erstat mine data',
  imported: 'Dine data er importeret.',
  exported: 'Filen er gemt.',
  saveFailed: 'Dine data kunne ikke gemmes i browseren.',
} as const;
