import { getLang } from '../../i18n';
import type { TaskType } from '../storage';

const MONTHS_DA = ['januar', 'februar', 'marts', 'april', 'maj', 'juni', 'juli', 'august', 'september', 'oktober', 'november', 'december'];
const MONTHS_EN = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

/** Al ordlyd i farvebehandlingens brugerflade på dansk. Ret her uden at røre layoutet; EN nedenfor har samme form. */
const DA = {
  title: 'Farvebehandling',
  back: 'Tilbage til forsiden',
  backToTraining: 'Tilbage til Træning',
  loading: 'Indlæser farvebehandling …',
  loadFailed: 'Banken kunne ikke hentes. Prøv igen, når du er online.',
  tabs: { training: 'Træning', practice: 'Selvvalgt', analysis: 'Analyse' },

  problem: 'Problemet',
  lines: 'Linjerne',
  difference: 'Forskellen',
  details: 'Sidningerne',
  north: 'Nord · bordet',
  south: 'Syd · dig',
  west: 'Vest',
  east: 'Øst',
  unknown: '?',
  /** Kompasset i bordets midte og de kort, modparten har. */
  compass: { N: 'N', W: 'V', E: 'Ø', S: 'S' },
  missing: (cards: string) => `${cards} mangler`,
  suit: '♠',
  goalLabel: 'Mål',
  goal: (n: number) => `${n} stik`,
  firstLead: (text: string) => `Første udspil: ${text}`,
  assumptions: 'a priori · ubegrænsede forbindelser · optimalt modspil',

  line: (letter: string) => `Linje ${letter}`,
  best: '✓ Bedste linje',
  equal: 'lige god',
  mixed: 'Chancen kræver, at du blander mellem to linjer.',
  chanceOf: (goal: number) => `Chance for ${goal} stik`,

  reaches: 'målet nås',
  misses: 'målet nås ikke',
  hit: '✓',
  miss: '✕',
  legend: 'Hvert felt er en sidning; bredden er chancen.',
  disagree: (n: number, list: string, more: number) =>
    `Linjerne er uenige i ${n === 1 ? '1 sidning' : `${n} sidninger`}: ${list}${more ? ` og ${more} til` : ''}.`,
  agree: 'Linjerne giver samme resultat i alle sidninger.',
  decisive: 'De afgørende sidninger',
  /** Mærket ved en sidning, hvor linjerne giver forskelligt resultat. */
  decides: 'afgør',
  groupBy: 'Gruppér',
  byDistribution: 'fordeling',
  byHonors: 'honnører',
  showAll: 'Vis alle sidninger',
  showFewer: 'Vis kun de afgørende',
  layout: (west: string, east: string) => `Vest ${west} – Øst ${east}`,
  fieldLabel: (west: string, east: string, chance: string, result: string) => `Vest ${west}, Øst ${east}: ${chance}, ${result}`,
  selected: 'Valgt sidning',

  result: 'Resultatet',
  bestChance: (goal: number, letter: string, chance: string) => `Bedste chance for ${goal} stik: ${chance} med linje ${letter}.`,
  pairs: (tricks: string, text: string) => `Bedst i parturnering: ${text} (${tricks} stik i gennemsnit).`,
  frequency: 'Hvor tit?',
  combination: (text: string) => `Kombinationen: ${text}.`,
  situation: (label: string, cards: number, text: string) => `${label} med ${cards} kort: ${text}.`,
  /** Situationen bag kombinationen, fx "Es og konge uden damen" eller "Uden esset". */
  situationLabel: (ours: readonly number[], theirs: readonly number[]) => {
    const some: Record<number, string> = { 14: 'es', 13: 'konge', 12: 'dame', 11: 'knægt' };
    const the: Record<number, string> = { 14: 'esset', 13: 'kongen', 12: 'damen', 11: 'knægten' };
    const names = ours.map((r) => some[r]);
    const list = names.length > 1 ? `${names.slice(0, -1).join(', ')} og ${names[names.length - 1]}` : (names[0] ?? '');
    const capital = (t: string) => t.charAt(0).toUpperCase() + t.slice(1);
    if (!theirs.length) return capital(list);
    return list ? `${capital(list)} uden ${the[theirs[0]]}` : `Uden ${the[theirs[0]]}`;
  },
  verified: 'Tallene stemmer med bridgehands.com.',
  unverified: 'Tallene afviger fra bridgehands.com; se valideringsrapporten.',

  choose: 'Vælg kombination',
  bank: 'Banken',
  bankHelp: 'Alle sider fra bridgehands.com, hyppigste først.',
  pageFilter: 'Modpartens honnørpoint',
  hp: (points: number) => (points === 0 ? 'ingen' : `${points} hp`),
  picker: 'Kortvælger',
  pickerHelp: 'Tryk på et kort én gang for bordet, to gange for din hånd og tre gange for at fjerne det.',
  pickerCard: (card: string, owner: string) => `${card}: ${owner}`,
  owners: { none: 'ingen', N: 'bordet', S: 'din hånd' },
  clear: 'Ryd',
  notInBank: 'Kombinationen findes ikke i banken. Løseren kan regne den her på telefonen; det tager typisk sekunder, store kombinationer op til et par minutter.',
  solveCustom: 'Regn den ud',
  solving: (seconds: number) => `Regner … ${seconds} s`,
  stopSolving: 'Stop',
  solveFailed: (message: string) => `Beregningen mislykkedes: ${message}`,
  goalNotSolved: 'Målet er ikke regnet endnu.',
  computedInApp: 'Regnet i appen; der er ingen kilde at sammenligne med.',

  ownLines: 'Dine linjer',
  addOwnLine: '+ Egen linje',
  ownLineTitle: (letter: string) => `Din linje ${letter}`,
  computeOwnLine: 'Regn',
  deleteOwnLine: 'Slet',
  ownLineNotComputed: 'Ikke regnet for dette mål endnu.',
  editorTitle: 'Egen linje',
  editorHelp: 'Byg linjen trin for trin. Efter sidste trin spiller løseren videre optimalt.',
  editorStep: (n: number) => `Trin ${n}`,
  editorLeadFrom: (n: number) => `Trin ${n}: udspil fra`,
  editorLeadFromShort: 'Udspil fra',
  editorNorth: 'bordet',
  editorSouth: 'hånden',
  editorCardShort: 'Kort',
  editorThirdLowShort: '3. hånd, når 2. hånd lægger lavt',
  editorThirdHighShort: '3. hånd, når 2. hånd lægger en honnør',
  editorCard: (n: number) => `Trin ${n}: kort`,
  editorThirdLow: (n: number) => `Trin ${n}: 3. hånd, når 2. hånd lægger lavt`,
  editorThirdHigh: (n: number) => `Trin ${n}: 3. hånd, når 2. hånd lægger en honnør`,
  editorRemove: (n: number) => `Fjern trin ${n}`,
  editorAdd: '+ Trin',
  editorName: 'Navn (valgfrit)',
  editorSave: 'Gem og regn',
  editorLow: 'lille',
  editorHigh: 'højt',
  /** Linjeeditorens navn på en linje: "Lille fra hånden; 3. hånd lægger …". */
  editorStepText: (lead: string, hand: 'N' | 'S', third?: { play: string; else: string }) =>
    `${lead.charAt(0).toUpperCase()}${lead.slice(1)} fra ${hand === 'N' ? 'bordet' : 'hånden'}${third ? `; 3. hånd lægger ${third.play}, men ${third.else}, hvis 2. hånd lægger en honnør` : ''}.`,
  editorCardName: (card: string) => (card === 'low' ? 'lille' : card === 'high' ? 'højt' : card),
  pickMore: 'Vælg kort til bordet og din hånd.',
  bankEntry: (rank: number, holding: string, often: string) => `${rank}. ${holding} · ${often}`,

  // Træning
  streak: 'Streak',
  daysInRow: (n: number): string => (n === 1 ? 'dag i træk' : 'dage i træk'),
  xp: 'XP',
  today: 'I dag',
  todayPlan: (due: number, fresh: number) =>
    `${due === 1 ? '1 emne' : `${due} emner`} til repetition · ${fresh === 1 ? '1 ny kombination' : `${fresh} nye kombinationer`}`,
  doneToday: 'Dagens session er gennemført. Du kan tage en til.',
  ownTrack: 'Farvebehandling har sin egen streak og XP, adskilt fra fordelingssporet.',
  start: 'Start dagens session',
  palace: 'Paladset',
  data: 'Dine data',
  phases: { repetition: 'Repetition', niveau: 'Niveau', lynrunde: 'Lynrunde', status: 'Status' },
  sessionMeta: (xp: number, combo: number) => `${xp} XP${combo >= 2 ? ` · combo ${combo}` : ''}`,
  stop: 'Afbryd sessionen',

  // Opgaverne
  goalPrompt: (n: number) => `Mål: ${n} stik`,
  chooseLine: 'Vælg linjen',
  guessPrompt: (n: number) => `Hvor stor er chancen for ${n} stik?`,
  guessOptional: 'Gæt chancen (valgfrit)',
  intervals: ['under 25 %', '25–50 %', '50–75 %', '75–100 %'],
  answer: 'Svar',
  theLine: 'Linjen',
  pickBest: 'Tryk på den bedste linje',
  newGoal: (before: number, now: number) => `Før var målet ${before} stik. Nu skal du have ${now} stik.`,
  findHole: 'Hvor taber linjen? Vælg sidningen.',
  whatNow: 'Hvad nu?',
  firstRound: 'Første runde',
  guessNow: (n: number) => `Hvor stor er chancen nu for ${n} stik?`,
  seats: { N: 'Nord', Ø: 'Øst', S: 'Syd', V: 'Vest' } as Record<string, string>,
  posteriorNote: 'Båndet viser kun de sidninger, der stadig er mulige, med deres chance efter første runde. Lagde en modspiller ét af to ligeværdige kort, tæller den sidning kun halvt (begrænset valg).',
  counting: 'Optællingen',
  countingHelp: 'Modspillerne har vist deres længder i de tre andre farver.',
  shown: (seat: string, suits: string, vacant: number) => `${seat}: ${suits} – ${vacant === 1 ? '1 ledig plads' : `${vacant} ledige pladser`}`,
  countingNote: 'Chancerne regnes med de ledige pladser.',
  suitSymbols: ['♠', '♥', '♦', '♣'],

  // Facit
  right: 'Rigtigt',
  half: 'Halvt rigtigt',
  wrong: 'Forkert',
  goodDecision: 'God beslutning.',
  halfDecision: 'Rigtig linje – chancen ligger i et andet interval.',
  betterLine: (letter: string) => `Linje ${letter} giver mere her.`,
  yourLine: (letter: string, ok: boolean) => `Du valgte linje ${letter} ${ok ? '✓' : '✕'}`,
  bestLine: (letter: string, chance: string) => `Bedst: linje ${letter} – ${chance}`,
  yourGuess: (interval: string, ok: boolean) => `Dit gæt: ${interval} ${ok ? '✓' : '✕'}`,
  noGuess: 'Intet gæt',
  chanceIs: (chance: string, interval: string) => `Chancen er ${chance}, altså ${interval}.`,
  holeIs: (layout: string) => `Linjen taber, når ${layout}.`,
  yourHole: (layout: string, ok: boolean) => `Dit valg: ${layout} ${ok ? '✓' : '✕'}`,
  gained: (xp: number, combo: number) => `+${xp} XP${combo >= 2 ? ` · ${combo} rigtige i træk` : ''}`,
  yourChoice: 'dit valg',
  why: 'Hvorfor →',
  back2: '← Facit',
  next: 'Næste opgave',
  memory: 'Huskeregel',
  image: 'Billede',
  room: (name: string, station: number | null) => (station ? `Rum: ${name} · station ${station}` : `Rum: ${name}`),
  scene: 'Din scene',
  allLayouts: 'Alle sidninger',

  // Spil den selv
  playTitle: 'Spil den selv',
  playTrick: 'Stikket',
  playButton: 'Spil den selv ▶',
  playLeadPrompt: 'Spil ud fra bordet eller hånden.',
  playThirdPrompt: (hand: string) => `Læg et kort fra ${hand === 'bordet' ? 'bordet' : 'hånden'}.`,
  playHidden: (n: number) => (n === 1 ? '? (1 kort)' : `? (${n} kort)`),
  playScore: (won: number, goal: number) => `Dine stik: ${won} · mål ${goal}`,
  playTrickWon: (n: number, seat: string) => `Stik ${n}: ${seat} vandt.`,
  playResult: (won: number, goal: number, made: boolean) =>
    made ? `${won} stik – målet på ${goal} er nået` : `${won} stik – målet var ${goal}`,
  playGoodMade: 'God beslutning – og målet blev nået.',
  playGoodUnlucky: 'God beslutning – sidningen var imod dig.',
  playLuckyMade: 'Målet blev nået, men en anden linje giver mere.',
  playFollowed: 'Du fulgte en af de bedste linjer ✓',
  playNotFollowed: 'Du fulgte ikke en af de bedste linjer ✕',
  playLayoutNote: 'Fordelingen, du spillede mod, lyser op i båndet.',
  playAgain: 'Ny fordeling',
  close: 'Luk',

  // Introduktion
  newCombination: 'Ny kombination',
  goalsText: (goals: readonly number[]) => `Mål: ${goals.map((g) => `${g} stik`).join(' og ')}`,
  newStation: (name: string, station: number) => `Rum: ${name} · ny station ${station}`,
  tryIt: 'Prøv den',

  // Status
  sessionDone: 'Dagens session er færdig',
  sessionScore: (correct: string, total: number) => `${correct} af ${total} rigtige`,
  sessionXp: (xp: number) => `+${xp} XP i dag`,
  tomorrow: (n: number) => `I morgen: ${n === 1 ? '1 emne' : `${n} emner`} til repetition.`,
  toHome: 'Færdig',

  // Selvvalgt
  practiceTitle: 'Vælg selv',
  practiceHelp: 'Øv det, du vil. Svarene logges, men ændrer ikke dagsplanen. Facit vises, når du har valgt linje.',
  filters: { technique: 'Teknik', cards: 'Antal kort', missing: 'Manglende honnører', goal: 'Mål' },
  all: 'Alle',
  option: (label: string, count: number) => `${label} (${count})`,
  cardsOption: (n: number) => `${n} kort`,
  goalOption: (n: number) => `${n} stik`,
  noHonors: 'ingen',
  startPractice: (n: number) => `Start · ${n === 1 ? '1 kombination' : `${n} kombinationer`}`,
  changeFilter: 'Skift filter',

  // Paladset
  palaceHelp: 'Hvert rum er en teknik, og stationerne er kombinationerne i den rækkefølge, du har mødt dem.',
  closedRooms: 'Lukkede rum',
  closedHelp: 'Et rum åbner, når dets første kombination dukker op i Træning.',
  edit: 'Ret',
  save: 'Gem',
  cancel: 'Annullér',
  standard: 'standard',
  own: 'dit eget',
  resetHint: 'Tom tekst giver standarden tilbage.',
  noScene: 'Ingen scene endnu.',
  editLabel: (what: string) => `Ret ${what.toLowerCase()}`,

  // Klubaften
  club: 'Klubaften',
  clubIntro: 'En klubaften er 25 spil. Felterne er de 100 kombinationer, du oftest møder, i rangorden.',
  clubGrid: 'De 100 hyppigste kombinationer',
  clubCell: (rank: number, holding: string, often: string) => `${rank}. ${holding}: ${often}`,
  clubHint: 'Tryk på et felt for at se kombinationen og hyppigheden.',
  clubName: (rank: number, holding: string) => `${rank}. ${holding}`,
  clubOften: (often: string, deals: string) => `${often} (1 ud af ${deals} spil)`,
  clubTechnique: (name: string, count: number) => `${name}: ${count} af de 100 kombinationer`,
  clubChip: (name: string, count: number) => `${name} × ${count}`,
  clubCards: (cards: readonly (readonly [number, number])[]) => `Kort i farven: ${cards.map(([n, c]) => `${n} kort ${c}`).join(' · ')}.`,
  clubList: 'Hyppighed',
  clubListFor: (name: string) => `Hyppighed · ${name}`,
  openInAnalysis: 'Åbn i Analyse',

  // Hold eller par
  formsHelp: 'I holdkamp gælder det om at nå målet, i parturnering om flest stik i gennemsnit. Hvilken linje spiller du hvor?',
  formName: (form: 'hold' | 'par', goal: number) => (form === 'hold' ? `Holdkamp, ${goal} stik` : 'Parturnering, flest stik'),
  lineName: (letter: string) => `Linje ${letter}`,
  yourForm: (form: string, chosen: string, right: string, ok: boolean) =>
    `${form}: du valgte linje ${chosen} ${ok ? '✓' : `✗ – linje ${right} er bedst`}`,
  formsTitle: 'Holdkamp og parturnering',
  formsLine: 'Linje',
  formsChance: (goal: number) => `${goal} stik`,
  formsTricks: 'Stik i gennemsnit',
  safetyCost: (letter: string, goal: number, gain: string, cost: string) =>
    `Linje ${letter} er sikkerhedsspillet: den giver ${goal} stik ${gain} procentpoint oftere, men koster ${cost} stik i gennemsnit.`,

  // Statistik
  stats: 'Statistik',
  statsHelp: 'Træfsikkerhed i Træning og Selvvalgt. Lynrunden tæller ikke med, og et halvt rigtigt svar tæller som et halvt.',
  statsEmpty: 'Ingen svar endnu. Statistikken tæller dine svar i Træning og Selvvalgt.',
  statsWeakest: (name: string, pct: string, n: number) => `Dit svageste punkt: ${name} med ${pct} rigtige af ${n} svar.`,
  statsPractice: 'Øv i Selvvalgt',
  statsPracticeOne: (name: string) => `Øv ${name.toLowerCase()} i Selvvalgt`,
  statsTechniques: 'Teknik',
  statsTasks: 'Opgavetype',
  statsAll: (pct: string, n: number) => `${pct} af ${n === 1 ? '1 svar' : `${n} svar`}`,
  statsNone: 'Ingen svar',
  statsRecent: (pct: string, n: number) => (n ? `Seneste 30 dage: ${pct} af ${n}` : 'Seneste 30 dage: ingen svar'),
  statsFew: (min: number) => `For få svar til at vurdere (mindst ${min}).`,
  taskNames: {
    'vælg-linjen': 'Vælg linjen',
    chancen: 'Hvor stor er chancen?',
    'linje-mod-linje': 'Linje mod linje',
    'nyt-mål': 'Samme farve, nyt mål',
    'hvad-nu': 'Hvad nu?',
    'find-hullet': 'Find hullet',
    'spil-selv': 'Spil den selv',
    optælling: 'Med optælling',
    'hold-eller-par': 'Hold eller par',
  } as Record<TaskType, string>,
  practiceSuggestion: (name: string, pct: string, n: number) => `Forslag: ${name} er dit svageste punkt med ${pct} rigtige af ${n} svar.`,
  practiceSuggestionPick: (name: string) => `Vælg ${name.toLowerCase()}`,

  // Dine data
  /** En dag som "4. oktober 2026". */
  dateText: (day: string) => {
    const [y, m, d] = day.split('-').map(Number);
    return `${d}. ${MONTHS_DA[m - 1]} ${y}`;
  },
  persistTitle: 'Fast lagring',
  persistFast: 'Fast lagring: ja. Browseren rydder ikke dine data af sig selv.',
  persistTemporary: 'Fast lagring: nej. Browseren kan rydde dine data, fx hvis telefonen mangler plads. Eksportér jævnligt.',
  persistUnknown: 'Browseren oplyser ikke, om dine data gemmes fast. Eksportér jævnligt.',
  persistAsk: 'Bed om fast lagring',
  lastExport: (date: string) => `Seneste eksport: ${date}.`,
  neverExported: 'Du har ikke eksporteret dine data endnu.',
  exportReminder: 'Det er over en måned siden, du sidst gemte en kopi af dine data. En kopi beskytter dem, hvis browseren rydder op.',
  exportNow: 'Eksportér nu',
  dataHelp: 'Farvebehandling gemmer alt i din browser under sin egen nøgle. Fordelingssporets data røres ikke.',
  exportData: 'Eksportér',
  importData: 'Importér',
  importFile: 'Vælg fil',
  importSummary: (xp: number, items: number, sessions: number, streak: number) =>
    `Filen har ${xp} XP, ${items} emner, ${sessions} sessioner og en streak på ${streak}.`,
  replace: 'Erstat mine data',
  imported: 'Dine data er importeret.',
  exported: 'Filen er gemt.',
  saveFailed: 'Dine data kunne ikke gemmes i browseren.',
  /** Importens fejlbeskeder fra storage.ts (på dansk); på engelsk oversættes de. */
  importError: (message: string) => message,

  // ⓘ: hjælp ved elementerne
  help: {
    tabs: 'Træning: din daglige session på ca. 5 minutter med nye kombinationer og repetition. Selvvalgt: vælg selv, hvad du vil øve, uden at dagsplanen ændres. Analyse: slå enhver kombination op og se linjerne, chancerne og sidningerne.',
    today: 'Repetition er emner (kombination × mål), som Leitner-systemet har sat til i dag. Nye kombinationer kommer i hyppighedsorden, højst 2 om dagen, og øves straks i hvert mål.',
    start: 'Sessionen: repetition (ca. 60 s), niveau med nye kombinationer og de senest introducerede, lynrunde med linje mod linje (60 s) og status. Dagen tæller i farvebehandlings egen streak.',
    palace: 'Hvert rum er en teknik med en huskeregel og et billede; stationerne er kombinationerne i den rækkefølge, du har mødt dem. Du kan skrive din egen huskeregel, dit eget billede og en scene til hver station.',
    club: 'De 100 kombinationer, du oftest møder, som 10 × 10 felter med hyppighed pr. klubaften. Tryk på et felt for detaljer; tekniknapperne fremhæver deres felter, og listen nedenunder har hyppigheden for alle.',
    stats: 'Træfsikkerhed pr. teknik og opgavetype, svageste først, for alle svar og de seneste 30 dage. Dit svageste punkt kan øves direkte i Selvvalgt.',
    data: 'Eksport og import af farvebehandlings data, fast lagring og hvornår du sidst eksporterede. Fordelingssporet har sin egen eksport under Indstillinger.',
    practice: 'Vælg filtre; tallet i parentes er antallet af kombinationer, og valg med 0 er grået ud. Start giver opgaver af blandede typer. Svarene logges til statistikken, men ændrer ikke dagsplanen.',
    band: 'Sandsynlighedsbåndet har én vandret søjle pr. linje, delt i sidninger efter deres chance. Mørkt felt med ✓: målet nås; lyst felt med ✕: målet nås ikke. Tryk på et felt for at se sidningen ved bordet.',
    lines: 'Linjerne med nummererede trin. "✓ bedst" markerer den bedste; linjer inden for 0,5 procentpoint er lige gode. Tallene forudsætter optimalt modspil og ubegrænsede forbindelser.',
    layouts: 'Alle sidninger af modpartens kort med chance og resultat for hver linje. Gruppér efter fordeling (Vests antal kort) eller efter honnørernes placering.',
    decides: 'Linjerne giver forskelligt resultat i denne sidning.',
    result: 'Bedste chance for målet, bedste linje i parturnering (flest stik i gennemsnit) og hvor tit kombinationen og situationen bag den forekommer.',
    choose: 'Vælg en kombination fra banken (hyppigste først; kan filtreres efter modpartens honnørpoint), eller byg den selv i kortvælgeren.',
    picker: 'Tryk på et kort én gang for bordet, to gange for din hånd og tre gange for at fjerne det. Findes kombinationen ikke i banken, kan løseren regne den på telefonen.',
    goals: 'Målet er det antal stik, du skal have. Den bedste linje kan skifte med målet; det er kernen i sikkerhedsspil.',
    ownLines: 'Byg din egen linje trin for trin og se dens chance ved siden af løserens. Efter sidste trin spiller løseren videre optimalt.',
    play: 'Spil ud fra bordet eller hånden, og læg 3. håndens kort. Modspillet lægger efter normalt modspil. Bagefter lyser fordelingen op i båndet, og du ser, om du fulgte en af de bedste linjer.',
    tasks: {
      'vælg-linjen': 'Vælg den linje, der giver størst chance for målet, og gæt chancen. Rigtig linje og rigtigt interval giver fuld score, rigtig linje og forkert interval halv.',
      chancen: 'Linjen er givet; gæt chancen for målet. Grænsen hører til intervallet over: 50,0 % er 50–75 %.',
      'linje-mod-linje': 'Tryk på den bedste af to linjer. Lynrunden bruger denne opgave.',
      'nyt-mål': 'Samme kombination, nyt mål: skifter den bedste linje med målet? Det er indgangen til sikkerhedsspil.',
      'hvad-nu': 'Første runde er spillet, og et kort er faldet. Vælg den bedste fortsættelse, og gæt chancen nu. Faldt en honnør, kan begrænset valg være nøglen.',
      'find-hullet': 'Linjen er givet; vælg den sidning (fordelingen af modpartens kort), hvor den taber.',
      'spil-selv': 'Spil farven kort for kort mod normalt modspil. Du bedømmes på beslutningen, ikke på resultatet: fulgte du en af de bedste linjer?',
      optælling: 'Modspillernes længder i de tre andre farver er kendt. Den med flest ledige pladser har oftest et bestemt kort, så chancerne ændrer sig.',
      'hold-eller-par': 'Vælg linjen til holdkamp (nå målet) og linjen til parturnering (flest stik i gennemsnit). Begge skal være rigtige.',
    } as Record<TaskType, string>,
  },
};

type Texts = typeof DA;

/** Al ordlyd på engelsk, i samme form som DA. */
const EN: Texts = {
  title: 'Suit combinations',
  back: 'Back to the front page',
  backToTraining: 'Back to Training',
  loading: 'Loading suit combinations …',
  loadFailed: 'The bank could not be loaded. Try again when you are online.',
  tabs: { training: 'Training', practice: 'Free practice', analysis: 'Analysis' },

  problem: 'The problem',
  lines: 'The lines',
  difference: 'The difference',
  details: 'The layouts',
  north: 'North · dummy',
  south: 'South · you',
  west: 'West',
  east: 'East',
  unknown: '?',
  compass: { N: 'N', W: 'W', E: 'E', S: 'S' },
  missing: (cards: string) => `${cards} missing`,
  suit: '♠',
  goalLabel: 'Goal',
  goal: (n: number) => `${n} ${n === 1 ? 'trick' : 'tricks'}`,
  firstLead: (text: string) => `First lead: ${text}`,
  assumptions: 'a priori · unlimited entries · best defence',

  line: (letter: string) => `Line ${letter}`,
  best: '✓ Best line',
  equal: 'equally good',
  mixed: 'The chance requires you to mix between two lines.',
  chanceOf: (goal: number) => `Chance of ${goal} ${goal === 1 ? 'trick' : 'tricks'}`,

  reaches: 'goal made',
  misses: 'goal not made',
  hit: '✓',
  miss: '✕',
  legend: 'Each field is a layout; the width is its chance.',
  disagree: (n: number, list: string, more: number) =>
    `The lines disagree in ${n === 1 ? '1 layout' : `${n} layouts`}: ${list}${more ? ` and ${more} more` : ''}.`,
  agree: 'The lines give the same result in every layout.',
  decisive: 'The decisive layouts',
  decides: 'decides',
  groupBy: 'Group',
  byDistribution: 'distribution',
  byHonors: 'honours',
  showAll: 'Show all layouts',
  showFewer: 'Show only the decisive ones',
  layout: (west: string, east: string) => `West ${west} – East ${east}`,
  fieldLabel: (west: string, east: string, chance: string, result: string) => `West ${west}, East ${east}: ${chance}, ${result}`,
  selected: 'Chosen layout',

  result: 'The result',
  bestChance: (goal: number, letter: string, chance: string) => `Best chance of ${goal} ${goal === 1 ? 'trick' : 'tricks'}: ${chance} with line ${letter}.`,
  pairs: (tricks: string, text: string) => `Best at pairs: ${text} (${tricks} tricks on average).`,
  frequency: 'How often?',
  combination: (text: string) => `The combination: ${text}.`,
  situation: (label: string, cards: number, text: string) => `${label} with ${cards} cards: ${text}.`,
  situationLabel: (ours: readonly number[], theirs: readonly number[]) => {
    const some: Record<number, string> = { 14: 'ace', 13: 'king', 12: 'queen', 11: 'jack' };
    const the: Record<number, string> = { 14: 'the ace', 13: 'the king', 12: 'the queen', 11: 'the jack' };
    const names = ours.map((r) => some[r]);
    const list = names.length > 1 ? `${names.slice(0, -1).join(', ')} and ${names[names.length - 1]}` : (names[0] ?? '');
    const capital = (t: string) => t.charAt(0).toUpperCase() + t.slice(1);
    if (!theirs.length) return capital(list);
    return list ? `${capital(list)} without ${the[theirs[0]]}` : `Without ${the[theirs[0]]}`;
  },
  verified: 'The figures agree with bridgehands.com.',
  unverified: 'The figures differ from bridgehands.com; see the validation report.',

  choose: 'Choose a combination',
  bank: 'The bank',
  bankHelp: 'All pages from bridgehands.com, most frequent first.',
  pageFilter: "Opponents' high-card points",
  hp: (points: number) => (points === 0 ? 'none' : `${points} HCP`),
  picker: 'Card picker',
  pickerHelp: 'Tap a card once for dummy, twice for your hand and three times to remove it.',
  pickerCard: (card: string, owner: string) => `${card}: ${owner}`,
  owners: { none: 'none', N: 'dummy', S: 'your hand' },
  clear: 'Clear',
  notInBank: 'The combination is not in the bank. The solver can work it out here on your phone; it usually takes seconds, large combinations up to a couple of minutes.',
  solveCustom: 'Work it out',
  solving: (seconds: number) => `Working … ${seconds} s`,
  stopSolving: 'Stop',
  solveFailed: (message: string) => `The calculation failed: ${message}`,
  goalNotSolved: 'This goal has not been worked out yet.',
  computedInApp: 'Worked out in the app; there is no source to compare with.',

  ownLines: 'Your lines',
  addOwnLine: '+ Own line',
  ownLineTitle: (letter: string) => `Your line ${letter}`,
  computeOwnLine: 'Work out',
  deleteOwnLine: 'Delete',
  ownLineNotComputed: 'Not worked out for this goal yet.',
  editorTitle: 'Own line',
  editorHelp: 'Build the line step by step. After the last step the solver plays on optimally.',
  editorStep: (n: number) => `Step ${n}`,
  editorLeadFrom: (n: number) => `Step ${n}: lead from`,
  editorLeadFromShort: 'Lead from',
  editorNorth: 'dummy',
  editorSouth: 'hand',
  editorCardShort: 'Card',
  editorThirdLowShort: '3rd hand when 2nd hand plays low',
  editorThirdHighShort: '3rd hand when 2nd hand plays an honour',
  editorCard: (n: number) => `Step ${n}: card`,
  editorThirdLow: (n: number) => `Step ${n}: 3rd hand when 2nd hand plays low`,
  editorThirdHigh: (n: number) => `Step ${n}: 3rd hand when 2nd hand plays an honour`,
  editorRemove: (n: number) => `Remove step ${n}`,
  editorAdd: '+ Step',
  editorName: 'Name (optional)',
  editorSave: 'Save and work out',
  editorLow: 'low',
  editorHigh: 'high',
  editorStepText: (lead: string, hand: 'N' | 'S', third?: { play: string; else: string }) =>
    `${lead.charAt(0).toUpperCase()}${lead.slice(1)} from ${hand === 'N' ? 'dummy' : 'hand'}${third ? `; 3rd hand plays ${third.play}, but ${third.else} if 2nd hand plays an honour` : ''}.`,
  editorCardName: (card: string) => (card === 'low' ? 'low' : card === 'high' ? 'high' : card),
  pickMore: 'Choose cards for dummy and your hand.',
  bankEntry: (rank: number, holding: string, often: string) => `${rank}. ${holding} · ${often}`,

  streak: 'Streak',
  daysInRow: (n: number) => (n === 1 ? 'day in a row' : 'days in a row'),
  xp: 'XP',
  today: 'Today',
  todayPlan: (due: number, fresh: number) =>
    `${due === 1 ? '1 item' : `${due} items`} to review · ${fresh === 1 ? '1 new combination' : `${fresh} new combinations`}`,
  doneToday: "Today's session is complete. You can take another one.",
  ownTrack: 'Suit combinations has its own streak and XP, separate from the distribution track.',
  start: "Start today's session",
  palace: 'The palace',
  data: 'Your data',
  phases: { repetition: 'Review', niveau: 'Level', lynrunde: 'Lightning round', status: 'Status' },
  sessionMeta: (xp: number, combo: number) => `${xp} XP${combo >= 2 ? ` · combo ${combo}` : ''}`,
  stop: 'Stop the session',

  goalPrompt: (n: number) => `Goal: ${n} ${n === 1 ? 'trick' : 'tricks'}`,
  chooseLine: 'Choose the line',
  guessPrompt: (n: number) => `How big is the chance of ${n} ${n === 1 ? 'trick' : 'tricks'}?`,
  guessOptional: 'Guess the chance (optional)',
  intervals: ['under 25 %', '25–50 %', '50–75 %', '75–100 %'],
  answer: 'Answer',
  theLine: 'The line',
  pickBest: 'Tap the best line',
  newGoal: (before: number, now: number) => `Before, the goal was ${before} tricks. Now you need ${now} tricks.`,
  findHole: 'Where does the line fail? Choose the layout.',
  whatNow: 'What now?',
  firstRound: 'First round',
  guessNow: (n: number) => `How big is the chance of ${n} ${n === 1 ? 'trick' : 'tricks'} now?`,
  seats: { N: 'North', Ø: 'East', S: 'South', V: 'West' } as Record<string, string>,
  posteriorNote: 'The band shows only the layouts that are still possible, with their chance after the first round. If a defender played one of two equal cards, that layout counts only half (restricted choice).',
  counting: 'The count',
  countingHelp: 'The defenders have shown their lengths in the other three suits.',
  shown: (seat: string, suits: string, vacant: number) => `${seat}: ${suits} – ${vacant === 1 ? '1 vacant place' : `${vacant} vacant places`}`,
  countingNote: 'The chances are calculated with the vacant places.',
  suitSymbols: ['♠', '♥', '♦', '♣'],

  right: 'Right',
  half: 'Half right',
  wrong: 'Wrong',
  goodDecision: 'Good decision.',
  halfDecision: 'Right line – the chance is in another interval.',
  betterLine: (letter: string) => `Line ${letter} gives more here.`,
  yourLine: (letter: string, ok: boolean) => `You chose line ${letter} ${ok ? '✓' : '✕'}`,
  bestLine: (letter: string, chance: string) => `Best: line ${letter} – ${chance}`,
  yourGuess: (interval: string, ok: boolean) => `Your guess: ${interval} ${ok ? '✓' : '✕'}`,
  noGuess: 'No guess',
  chanceIs: (chance: string, interval: string) => `The chance is ${chance}, so ${interval}.`,
  holeIs: (layout: string) => `The line fails when ${layout}.`,
  yourHole: (layout: string, ok: boolean) => `Your choice: ${layout} ${ok ? '✓' : '✕'}`,
  gained: (xp: number, combo: number) => `+${xp} XP${combo >= 2 ? ` · ${combo} right in a row` : ''}`,
  yourChoice: 'your choice',
  why: 'Why →',
  back2: '← Answer',
  next: 'Next task',
  memory: 'Memory rule',
  image: 'Image',
  room: (name: string, station: number | null) => (station ? `Room: ${name} · station ${station}` : `Room: ${name}`),
  scene: 'Your scene',
  allLayouts: 'All layouts',

  playTitle: 'Play it yourself',
  playTrick: 'The trick',
  playButton: 'Play it yourself ▶',
  playLeadPrompt: 'Lead from dummy or from your hand.',
  // Hånden kommer som TEXT.owners: "dummy" eller "your hand".
  playThirdPrompt: (hand: string) => `Play a card from ${hand}.`,
  playHidden: (n: number) => (n === 1 ? '? (1 card)' : `? (${n} cards)`),
  playScore: (won: number, goal: number) => `Your tricks: ${won} · goal ${goal}`,
  playTrickWon: (n: number, seat: string) => `Trick ${n}: ${seat} won.`,
  playResult: (won: number, goal: number, made: boolean) =>
    made ? `${won} ${won === 1 ? 'trick' : 'tricks'} – the goal of ${goal} is made` : `${won} ${won === 1 ? 'trick' : 'tricks'} – the goal was ${goal}`,
  playGoodMade: 'Good decision – and the goal was made.',
  playGoodUnlucky: 'Good decision – the layout was against you.',
  playLuckyMade: 'The goal was made, but another line gives more.',
  playFollowed: 'You followed one of the best lines ✓',
  playNotFollowed: 'You did not follow one of the best lines ✕',
  playLayoutNote: 'The layout you played against lights up in the band.',
  playAgain: 'New deal',
  close: 'Close',

  newCombination: 'New combination',
  goalsText: (goals: readonly number[]) => `Goal: ${goals.map((g) => `${g} ${g === 1 ? 'trick' : 'tricks'}`).join(' and ')}`,
  newStation: (name: string, station: number) => `Room: ${name} · new station ${station}`,
  tryIt: 'Try it',

  sessionDone: "Today's session is finished",
  sessionScore: (correct: string, total: number) => `${correct} of ${total} right`,
  sessionXp: (xp: number) => `+${xp} XP today`,
  tomorrow: (n: number) => `Tomorrow: ${n === 1 ? '1 item' : `${n} items`} to review.`,
  toHome: 'Done',

  practiceTitle: 'Choose yourself',
  practiceHelp: 'Practise what you want. Answers are logged but do not change the daily plan. The answer is shown once you have chosen a line.',
  filters: { technique: 'Technique', cards: 'Number of cards', missing: 'Missing honours', goal: 'Goal' },
  all: 'All',
  option: (label: string, count: number) => `${label} (${count})`,
  cardsOption: (n: number) => `${n} cards`,
  goalOption: (n: number) => `${n} ${n === 1 ? 'trick' : 'tricks'}`,
  noHonors: 'none',
  startPractice: (n: number) => `Start · ${n === 1 ? '1 combination' : `${n} combinations`}`,
  changeFilter: 'Change filter',

  palaceHelp: 'Each room is a technique, and the stations are the combinations in the order you met them.',
  closedRooms: 'Closed rooms',
  closedHelp: 'A room opens when its first combination turns up in Training.',
  edit: 'Edit',
  save: 'Save',
  cancel: 'Cancel',
  standard: 'standard',
  own: 'your own',
  resetHint: 'Empty text restores the standard.',
  noScene: 'No scene yet.',
  editLabel: (what: string) => `Edit ${what.toLowerCase()}`,

  club: 'Club evening',
  clubIntro: 'A club evening is 25 boards. The fields are the 100 combinations you meet most often, in order of rank.',
  clubGrid: 'The 100 most frequent combinations',
  clubCell: (rank: number, holding: string, often: string) => `${rank}. ${holding}: ${often}`,
  clubHint: 'Tap a field to see the combination and how often it occurs.',
  clubName: (rank: number, holding: string) => `${rank}. ${holding}`,
  clubOften: (often: string, deals: string) => `${often} (1 in ${deals} boards)`,
  clubTechnique: (name: string, count: number) => `${name}: ${count} of the 100 combinations`,
  clubChip: (name: string, count: number) => `${name} × ${count}`,
  clubCards: (cards: readonly (readonly [number, number])[]) => `Cards in the suit: ${cards.map(([n, c]) => `${n} cards ${c}`).join(' · ')}.`,
  clubList: 'Frequency',
  clubListFor: (name: string) => `Frequency · ${name}`,
  openInAnalysis: 'Open in Analysis',

  formsHelp: 'At teams the point is to make the goal, at pairs to make the most tricks on average. Which line do you play where?',
  formName: (form: 'hold' | 'par', goal: number) => (form === 'hold' ? `Teams, ${goal} tricks` : 'Pairs, most tricks'),
  lineName: (letter: string) => `Line ${letter}`,
  yourForm: (form: string, chosen: string, right: string, ok: boolean) =>
    `${form}: you chose line ${chosen} ${ok ? '✓' : `✗ – line ${right} is best`}`,
  formsTitle: 'Teams and pairs',
  formsLine: 'Line',
  formsChance: (goal: number) => `${goal} tricks`,
  formsTricks: 'Tricks on average',
  safetyCost: (letter: string, goal: number, gain: string, cost: string) =>
    `Line ${letter} is the safety play: it makes ${goal} tricks ${gain} percentage points more often, but costs ${cost} tricks on average.`,

  stats: 'Statistics',
  statsHelp: 'Accuracy in Training and Free practice. The lightning round does not count, and a half-right answer counts as a half.',
  statsEmpty: 'No answers yet. The statistics count your answers in Training and Free practice.',
  statsWeakest: (name: string, pct: string, n: number) => `Your weakest spot: ${name} with ${pct} right of ${n} answers.`,
  statsPractice: 'Practise in Free practice',
  statsPracticeOne: (name: string) => `Practise ${name.toLowerCase()} in Free practice`,
  statsTechniques: 'Technique',
  statsTasks: 'Task type',
  statsAll: (pct: string, n: number) => `${pct} of ${n === 1 ? '1 answer' : `${n} answers`}`,
  statsNone: 'No answers',
  statsRecent: (pct: string, n: number) => (n ? `Last 30 days: ${pct} of ${n}` : 'Last 30 days: no answers'),
  statsFew: (min: number) => `Too few answers to judge (at least ${min}).`,
  taskNames: {
    'vælg-linjen': 'Choose the line',
    chancen: 'How big is the chance?',
    'linje-mod-linje': 'Line against line',
    'nyt-mål': 'Same suit, new goal',
    'hvad-nu': 'What now?',
    'find-hullet': 'Find the hole',
    'spil-selv': 'Play it yourself',
    optælling: 'With counting',
    'hold-eller-par': 'Teams or pairs',
  } as Record<TaskType, string>,
  practiceSuggestion: (name: string, pct: string, n: number) => `Suggestion: ${name} is your weakest spot with ${pct} right of ${n} answers.`,
  practiceSuggestionPick: (name: string) => `Choose ${name.toLowerCase()}`,

  dateText: (day: string) => {
    const [y, m, d] = day.split('-').map(Number);
    return `${d} ${MONTHS_EN[m - 1]} ${y}`;
  },
  persistTitle: 'Persistent storage',
  persistFast: 'Persistent storage: yes. The browser will not clear your data on its own.',
  persistTemporary: 'Persistent storage: no. The browser may clear your data, e.g. if the phone runs out of space. Export regularly.',
  persistUnknown: 'The browser does not say whether your data is stored persistently. Export regularly.',
  persistAsk: 'Ask for persistent storage',
  lastExport: (date: string) => `Last export: ${date}.`,
  neverExported: 'You have not exported your data yet.',
  exportReminder: 'It has been more than a month since you last saved a copy of your data. A copy protects it if the browser clears its storage.',
  exportNow: 'Export now',
  dataHelp: 'Suit combinations saves everything in your browser under its own key. The distribution track’s data is not touched.',
  exportData: 'Export',
  importData: 'Import',
  importFile: 'Choose file',
  importSummary: (xp: number, items: number, sessions: number, streak: number) =>
    `The file has ${xp} XP, ${items} items, ${sessions} sessions and a streak of ${streak}.`,
  replace: 'Replace my data',
  imported: 'Your data has been imported.',
  exported: 'The file has been saved.',
  saveFailed: 'Your data could not be saved in the browser.',
  importError: (message: string) =>
    ({
      'Filen er ikke gyldig JSON.': 'The file is not valid JSON.',
      'Filen indeholder ikke data fra farvebehandling.': 'The file does not contain suit combinations data.',
      'Filen er fra en nyere version af appen.': 'The file is from a newer version of the app.',
    })[message] ?? message.replace(/^Filen er ugyldig: /, 'The file is invalid: '),

  help: {
    tabs: 'Training: your daily session of about 5 minutes with new combinations and review. Free practice: choose for yourself what to practise without changing the daily plan. Analysis: look up any combination and see the lines, the chances and the layouts.',
    today: 'Review is the items (combination × goal) the Leitner system has scheduled for today. New combinations arrive in order of frequency, at most 2 a day, and are practised at once in each goal.',
    start: 'The session: review (about 60 s), level with new combinations and the most recently introduced ones, a lightning round with line against line (60 s) and status. The day counts in the suit combinations streak.',
    palace: 'Each room is a technique with a memory rule and an image; the stations are the combinations in the order you met them. You can write your own memory rule, your own image and a scene for each station.',
    club: 'The 100 combinations you meet most often, as 10 × 10 fields with their frequency per club evening. Tap a field for details; the technique buttons highlight their fields, and the list below has the frequency of all of them.',
    stats: 'Accuracy per technique and task type, weakest first, for all answers and the last 30 days. Your weakest spot can be practised directly in Free practice.',
    data: 'Export and import of the suit combinations data, persistent storage and when you last exported. The distribution track has its own export under Settings.',
    practice: 'Choose filters; the number in brackets is the number of combinations, and choices with 0 are greyed out. Start gives tasks of mixed types. Answers are logged for the statistics but do not change the daily plan.',
    band: 'The probability band has one horizontal bar per line, divided into layouts by their chance. Dark field with ✓: goal made; light field with ✕: goal not made. Tap a field to see the layout at the table.',
    lines: 'The lines with numbered steps. "✓ best" marks the best one; lines within 0.5 percentage points are equally good. The figures assume best defence and unlimited entries.',
    layouts: "All layouts of the opponents' cards with the chance and result for each line. Group by distribution (West's number of cards) or by where the honours are.",
    decides: 'The lines give different results in this layout.',
    result: 'The best chance of the goal, the best line at pairs (most tricks on average) and how often the combination and the situation behind it occur.',
    choose: "Choose a combination from the bank (most frequent first; can be filtered by the opponents' high-card points), or build it yourself in the card picker.",
    picker: 'Tap a card once for dummy, twice for your hand and three times to remove it. If the combination is not in the bank, the solver can work it out on your phone.',
    goals: 'The goal is the number of tricks you need. The best line can change with the goal; that is the heart of safety play.',
    ownLines: "Build your own line step by step and see its chance next to the solver's. After the last step the solver plays on optimally.",
    play: 'Lead from dummy or your hand, and play the 3rd-hand card. The defenders play normal defence. Afterwards the layout lights up in the band, and you see whether you followed one of the best lines.',
    tasks: {
      'vælg-linjen': 'Choose the line that gives the best chance of the goal, and guess the chance. Right line and right interval give a full score, right line and wrong interval half.',
      chancen: 'The line is given; guess the chance of the goal. A boundary belongs to the interval above: 50.0 % is 50–75 %.',
      'linje-mod-linje': 'Tap the better of two lines. The lightning round uses this task.',
      'nyt-mål': 'Same combination, new goal: does the best line change with the goal? This is the way into safety play.',
      'hvad-nu': 'The first round has been played, and a card has fallen. Choose the best continuation and guess the chance now. If an honour fell, restricted choice may be the key.',
      'find-hullet': "The line is given; choose the layout (distribution of the opponents' cards) where it fails.",
      'spil-selv': 'Play the suit card by card against normal defence. You are judged on the decision, not the result: did you follow one of the best lines?',
      optælling: "The defenders' lengths in the other three suits are known. The one with more vacant places is more likely to hold a given card, so the chances change.",
      'hold-eller-par': 'Choose the line for teams (make the goal) and the line for pairs (most tricks on average). Both must be right.',
    } as Record<TaskType, string>,
  },
};

/** Ordlyden på det aktuelle sprog (dansk eller engelsk). */
export const TEXT: Texts = new Proxy(DA, {
  get: (_target, key) => (getLang() === 'en' ? EN : DA)[key as keyof Texts],
});
